services:
  api:
    image: okteto.dev/api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080
environment:
  TELEGRAM_TOKEN: ${TELEGRAM_TOKEN}
endpoints:
  - path: /
    service: api
    port: 8080