services:
  api:
    image: okteto.dev/api
    environment:
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080

endpoints:
  - path: /
    service: api
    port: 8080